FIND_PATH(ACE_INCLUDE_DIR ACE.h
		$ENV{ACE_ROOT}/ace
)

SET(ACE_FOUND FALSE)

IF(ACE_INCLUDE_DIR)
	FIND_LIBRARY(ACE_LIBRARY ACE
			 $ENV{ACE_ROOT}/lib
	)
	IF(ACE_LIBRARY)
		SET(ACE_FOUND TRUE)
	ENDIF(ACE_LIBRARY)
ENDIF(ACE_INCLUDE_DIR)

IF(ACE_FOUND)
	MESSAGE(STATUS "Found ACE: ${ACS_INCLUDE_DIR}")
ELSE(ACE_FOUND)
	MESSAGE(FATAL_ERROR "ACE was not found. ${ACS_INCLUDE_DIR}")
ENDIF(ACE_FOUND)
